### ISSUE TITLE
LaserPrinter class

### ISSUE THREAD

**Issue by DenisLabrecque** [DenisLabrecque/Java#1]
Create constants to define:
• None at this time
Create data types:
- [x] Power status (on/off)
- [x] All the subclasses needed
Create methods:
- [x] Power on/off printer
- [x] Load paper
- [x] Load toner
- [x] Replace drum
- [x] Add/Print/Cancel/Remove document from queue (Simulates real world sending a job to printer, managing the
queue, and the printer consuming documents from the queue).
- [x] Status report
- [x] Testing health of each assembly and setting the display correctly in response

**Comment by DenisLabrecque** [comment]
@thorkitty You will need to implement loading the paper from the laser printer class, as that interacts with your class interface. I've got a lot on my plate right now.

Also, make sure there's an appropriate status if necessary (percent full, number of pages, or whatever is from `getValue()`).

**Comment by DenisLabrecque** [comment]
@c1m2k399 You'll probably end up implementing the load toner stuff. Check it off once it gets done. Also make sure we can get an appropriate status for the status report (from `getValue()` or similar).

**Comment by DenisLabrecque** [comment]
@lazybookwyrm You'll end up having a method to replace the drum. Make sure your status report includes a correct value for the drum.

**Comment by DenisLabrecque** [comment]
@ZahinU Please make sure your class has a correct report when we type `STATUS` as a command.

**Comment by ZahinU** [comment]
> @ZahinU Please make sure your class has a correct report when we type `STATUS` as a command.

@DenisLabrecque your referring to the Output Assembly?

**Comment by DenisLabrecque** [comment]
> > @ZahinU Please make sure your class has a correct report when we type `STATUS` as a command.
> 
> @DenisLabrecque your referring to the Output Assembly?

Yes, with `getValue()` mandated by `AssemblyUnit` or whatever else is necessary to give insight on how full it is

**Comment by DenisLabrecque** [comment]
Still need to figure out exactly how to finish turning the printer on once something goes wrong in turning on.
