### ISSUE TITLE
TonerAssembly

### ISSUE THREAD

**Issue by DenisLabrecque** [DenisLabrecque/Java#4]
Create constants to define:
   - [ ] Number of printed sheets that a full toner can print (do some research by searching HP website on toner yield).
   - [ ] Level of toner (in sheets) where a warning would be issued that the toner is getting low
   - [ ] Level of toner (in sheets) where printer stops printing. Typically toners don’t go to zero but rather stop before they are completely empty.
Create data types:
   - [ ] Number of sheets printed
Create methods:
   - [ ] Consume toner, simulating toner being used while printing
   - [ ] Reload toner, simulating the replacement of a toner cartridge
   - [ ] Test to see if warning should be issued.

**Comment by thorkitty** [comment]
@c1m2k399 there is no instructions on the deactivate function.
